// server/utils/contentHelpers.js

/**
 * Normalize tags array to lowercase and remove empty values
 */
const normalizeTags = (tags) => {
  if (!tags) return [];
  return Array.isArray(tags)
    ? tags.map((tag) => (tag || "").toLowerCase().trim()).filter(Boolean)
    : [];
};

/**
 * Validate code submissions with basic checks
 */
const validateCodeSubmission = (userCode, exercise) => {
  // Basic empty check
  if (!userCode || userCode.trim() === "") {
    return {
      isCorrect: false,
      feedback: "Please write some code before submitting!",
    };
  }

  // Check if user just submitted starter code
  if (exercise.starterCode && userCode.trim() === exercise.starterCode.trim()) {
    return {
      isCorrect: false,
      feedback: "Please modify the starter code with your solution!",
    };
  }

  // Check for empty assignments or placeholder comments
  const lines = userCode.split("\n");
  const hasEmptyAssignments = lines.some((line) => {
    return line.match(/^\s*\w+\s*=\s*$/);
  });

  const hasPlaceholderComments = lines.some((line) => {
    return line.match(/#\s*(TODO|FIXME|your code here|fill in)/i);
  });

  if (hasEmptyAssignments || hasPlaceholderComments) {
    return {
      isCorrect: false,
      feedback: "Please complete all the code assignments before submitting!",
    };
  }

  // TODO: Add more sophisticated validation later
  return {
    isCorrect: true,
    feedback: "Great job! Your code looks good.",
  };
};

/**
 * Normalizes lesson tags and creates the lesson completion history record
 * @param {object} lesson - The lesson document
 * @param {object} submissionBody - The req body containing submission details
 * @param {Date} completionTimestamp - The timestamp of completion
 * @returns {object} - The lesson completion record object
 */
const createLessonCompletionRecord = (
  lesson,
  submissionBody,
  completionTimestamp
) => {
  if (!lesson || !completionTimestamp) {
    throw new Error("Lesson and completionTimestamp are required");
  }

  const {
    elapsedSeconds,
    usedHints = false,
    attemptNumber = 1,
    linesOfCode,
    wasOptimalSolution = false,
  } = submissionBody;

  const normalizedTags = normalizeTags(lesson.tags);

  const lessonRecord = {
    lessonId: lesson._id.toString(),
    completedAt: completionTimestamp,
    tags: normalizedTags,
    contentType: lesson.contentType,
    difficulty: lesson.difficulty,
    challengeGroup: lesson.challengeGroup
      ? lesson.challengeGroup.toLowerCase()
      : undefined,
  };

  if (typeof elapsedSeconds === "number" && elapsedSeconds >= 0) {
    lessonRecord.elapsedSeconds = elapsedSeconds;
  }
  if (typeof attemptNumber === "number" && attemptNumber >= 1) {
    lessonRecord.attemptNumber = attemptNumber;
  }
  if (typeof linesOfCode === "number" && linesOfCode >= 0) {
    lessonRecord.linesOfCode = linesOfCode;
  }
  lessonRecord.usedHints = !!usedHints;
  lessonRecord.wasOptimal = !!wasOptimalSolution;

  return lessonRecord;
};

/**
 * Updates various challenge statistics on the User document based on a lesson completion.
 * @param {object} user The Mongoose User document.
 * @param {object} lessonRecord The lesson completion record generated by createLessonCompletionRecord.
 * @param {object} submissionBody The request body containing submission details (elapsedSeconds, attemptNumber, etc.).
 */
const updateUserStats = (user, lessonRecord, submissionBody) => {
  if (!user || !lessonRecord) {
    throw new Error("User and lessonRecord are required");
  }

  user.stats = user.stats || {};

  const ensureStat = (key) => {
    if (typeof user.stats[key] !== "number") {
      user.stats[key] = 0;
    }
  };

  const isChallengeLesson = lessonRecord.contentType !== "theory";
  const difficultyLevel = (lessonRecord.difficulty || "").toLowerCase();
  const isMediumOrHard =
    difficultyLevel === "intermediate" ||
    difficultyLevel === "advanced" ||
    difficultyLevel === "expert";

  const {
    elapsedSeconds,
    usedHints = false,
    attemptNumber = 1,
    wasOptimalSolution = false,
  } = submissionBody;

  if (isChallengeLesson) {
    // Tags are already normalized in lessonRecord
    const normalizedTags = lessonRecord.tags;

    // Fast Challenge Count
    if (
      typeof elapsedSeconds === "number" &&
      elapsedSeconds > 0 &&
      elapsedSeconds <= 30
    ) {
      ensureStat("fastChallengeCount");
      user.stats.fastChallengeCount += 1;
    }

    // First Try Challenge Count
    if (Number(attemptNumber) === 1 && !usedHints && isMediumOrHard) {
      ensureStat("firstTryChallengeCount");
      user.stats.firstTryChallengeCount += 1;
    }

    // Optimal Solution Count
    if (wasOptimalSolution) {
      ensureStat("optimalSolutionCount");
      user.stats.optimalSolutionCount += 1;
    }

    // Tag-based counts
    if (normalizedTags.includes("functions")) {
      ensureStat("functionChallengeCount");
      user.stats.functionChallengeCount += 1;
    }

    if (
      normalizedTags.includes("api") ||
      normalizedTags.includes("apis") ||
      normalizedTags.includes("http") ||
      normalizedTags.includes("requests")
    ) {
      ensureStat("apiChallengeCount");
      user.stats.apiChallengeCount += 1;
    }

    if (
      normalizedTags.includes("file-io") ||
      normalizedTags.includes("files") ||
      normalizedTags.includes("fileio") ||
      normalizedTags.includes("csv")
    ) {
      ensureStat("fileChallengeCount");
      user.stats.fileChallengeCount += 1;
    }

    if (
      normalizedTags.includes("regex") ||
      normalizedTags.includes("regular-expressions")
    ) {
      ensureStat("regexChallengeCount");
      user.stats.regexChallengeCount += 1;
    }
  }
};

module.exports = {
  normalizeTags,
  validateCodeSubmission,
  createLessonCompletionRecord,
  updateUserStats,
};
